all: test.o

test.o: test.c
	gcc -c test.c -o test.o
###

simple::
	./driver.sh aborter2
	./driver.sh aborter
	./driver.sh a_case_of_the_splits
	./driver.sh activeBlock
	./driver.sh activeFocus
	./driver.sh active
	./driver.sh agg
	./driver.sh ahead
	./driver.sh alert
	./driver.sh align
	./driver.sh appjs
	./driver.sh ascdesc
	echo ./driver.sh attrMangle
	./driver.sh attrs_escape
	echo ./driver.sh attrs
	./driver.sh autocomp
	./driver.sh babySpawn
	./driver.sh bindpat
	./driver.sh bodyClick
	./driver.sh bool
	./driver.sh both
	./driver.sh both2
	./driver.sh button
	./driver.sh case
	./driver.sh caseMod
	./driver.sh ccheckbox
	./driver.sh cdataF
	./driver.sh cdataL
	./cffi.sh
	./driver.sh cfold_disj
	./driver.sh char
	./driver.sh checkbox
	./driver.sh classAndDynClass
	./driver.sh classy_form
	./driver.sh coalesce
	./driver.sh comment
	./driver.sh concat
	./driver.sh consub
	./driver.sh contentDisposition
	./driver.sh cselect
	./driver.sh css
	./driver.sh cssNull
	./driver.sh cst
	./driver.sh ctextarea
	./driver.sh ctextbox
	./driver.sh ctextboxAttrs
	./driver.sh ctuple
	./driver.sh cut
	./driver.sh cyrillic
	./driver.sh DynChannel
	./driver.sh jsonTest
	./driver.sh entities
	./driver.sh fact
	./driver.sh filter
	./driver.sh jsbspace
	./driver.sh utf8
